### ISSUE TITLE
Installation fails in mac

### ISSUE THREAD

**Issue by brijeshgp** [echoma/zkui#10]
Traceback (most recent call last):
  File "./zkui.py", line 5, in <module>
    from WebWindow import WebWindow
  File "WebWindow.py", line 1, in <module>
    from PyQt5 import QtCore, QtWidgets, QtWebKitWidgets, QtNetwork, QtWebKit, QtPrintSupport
ImportError: cannot import name 'QtWebKitWidgets'

**Comment by echoma** [comment]
Qt5.6 removed QtWebkit. So, Qt5.5 is the newest version we can use to build zkui.

I was planning to port zkui to nw.js, but doesn't have enough spare time yet.

Sorry for wasting your time, I will put a note into README.

**Comment by davegallant** [comment]
```
Collecting PyQt5==5.5
  Could not find a version that satisfies the requirement PyQt5==5.5 (from versions: 5.6, 5.7, 5.7.1, 5.8, 5.8.1.1)
```
Cannot find this in pip.

**Comment by echoma** [comment]
oh, there are no earlier version in pip?  can you try 5.3 or 5.4?

**Comment by davegallant** [comment]
@echoma I don't think they exist in pypi: https://pypi.python.org/pypi/PyQt5/

**Comment by echoma** [comment]
@davey-dev So, it seems that the only solution is a refactor. Large work to do, damn...
