### ISSUE TITLE
ImportError: cannot import name 'QtWebKitWidgets' from 'PyQt5' 

### ISSUE THREAD

**Issue by haipop** [echoma/zkui#15]
我本地的qt版本是5.11 ,mac 环境，Python3.7 , 貌似新版本的pyqt已经没有这个QtWebKitWidgets
Requirement already satisfied: pyqt5 in /usr/local/lib/python3.7/site-packages (5.11.2)
Requirement already satisfied: PyQt5_sip<4.20,>=4.19.11 in /usr/local/lib/python3.7/site-packages (from pyqt5) (4.19.12)
`Traceback (most recent call last):
  File "./zkui.py", line 5, in <module>
    from WebWindow import WebWindow
  File "/Users/haipop/Work/Code/util/zkui/WebWindow.py", line 14, in <module>
    from PyQt5 import QtCore, QtWidgets, QtWebKitWidgets
ImportError: cannot import name 'QtWebKitWidgets' from 'PyQt5' (/usr/local/lib/python3.7/site-packages/PyQt5/__init__.py)`

**Comment by echoma** [comment]
我记得是从QT5.4开始QtWebkit组件就被干掉了，我这边暂时没有精力维护这个东西了，十分抱歉。暂时只能用已经打包好的Windows版本了，想自己build比较困难了。

**Comment by sonymoon** [comment]
mac能否build一个dmg版本的。pyqt5.5 pip找不到了

**Comment by echoma** [comment]
@sonymoon 我一方面不懂mac上的打包，另一方面目前实在没有精力维护zkui。如果要自己build，要找pyqt5.4以前的版本。
